#!/bin/bash

echo "< Making directory /usr/share/doc/hank >"
sudo mkdir /usr/share/doc/hank
echo "< Moving hankquotes to /usr/share/doc/hank >"
sudo mv hankquotes /usr/share/doc/hank
echo "< Moving hank to /usr/games >"
sudo mv hank /usr/games
echo "< Giving hank executable permissions >"
sudo chmod +x /usr/games/hank
echo "Done! Now simply run "hank" in the terminal to use hank!"
echo "If you want, add more quotes to the 'hankquotes' file or edit the $file variable in 'hank' to use a custom file."
